spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    open-in-view: true
  datasource:
    url: "jdbc:postgresql://s1_database:5432/db"
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
